config/routes.rb
Rails.application.routes.draw do
  get 'google/distance'
  get 'google/address'

  get 'gender/determine'

  get 'weather/search'
  resources :gender
  resources :google

  namespace :api, format: 'json' do
    namespace :v1 do
      resources :categories
      resources :products
    end
  end

   root 'weather#search'

end

app/models/category.rb
class Category < ActiveRecord::Base
has_many :products
validates_presence_of :name
end

app/models/product.rb
class Product < ActiveRecord::Base
belongs_to :category

validates_presence_of :name,:price,:category_id

end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ApplicationController

def index
	@categories = Category.all
	
end

end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ApplicationController

def index
	@products = Product.all
	
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gender_controller.rb
class GenderController < ApplicationController
  def determine
  	if params[:name]
  		response = HTTParty.get("https://gender-api.com/get?name=#{params[:name]}")

  		@result = JSON.parse(response.body)
  	end
  end
end

app/controllers/google_controller.rb
class GoogleController < ApplicationController
  def distance
  	if params[:origin] && params[:destination]
  		response = HTTParty.get("http://maps.googleapis.com/maps/api/distancematrix/json?origins=#{params[:origin]}&destinations=#{params[:destination]}")
  		@result = JSON.parse(response.body)
  	end
  end
  def address
  	if params[:address]
  		response = HTTParty.get("http://maps.googleapis.com/maps/api/geocode/json?&address=#{params[:address]}")

  		@result = JSON.parse(response.body)
  		
  		

  	end
  	
  end
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def search
  	if params[:name]
  		response = HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{params[:name]}&APPID=3ae18949940ecdb295e65ef1a2186a0f&units=metric")
  		@result = JSON.parse(response.body)
  	end
  end
end

app/helpers/api/v1/categories_helper.rb
module Api::V1::CategoriesHelper
end

app/helpers/api/v1/products_helper.rb
module Api::V1::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gender_helper.rb
module GenderHelper
end

app/helpers/google_helper.rb
module GoogleHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/gender/determine.html.erb
<h2>Determining Gender</h2>

<%= form_tag(gender_determine_path, method: :get) do%>

	<label>Name:</label><br>
	<%= text_field_tag :name%><br>

	<%= submit_tag "Submit"%>

<%end%>

<% if !@result.nil?%>
<h2>Gender:<%=@result["gender"]%></h2>
	<%end%>

app/views/google/address.html.erb
<h2>Find address</h2>

<%=form_tag(google_address_path, method: :get) do %>

	<label>Address:</label><br>
	<%= text_area_tag :address, params[:address]%><br>

	<%= submit_tag "search"%>

<%end%>

<%if !@result.nil?%>
	<h3>lat:<%= @result["results"][0]["geometry"]["location"]["lat"]%></h3>
	<h3>log:<%= @result["results"][0]["geometry"]["location"]["lng"]%></h3>
	<h3>city:<%=  @result["results"][0]["address_components"][2]["long_name"]%></h3>
	<%end%>

app/views/google/distance.html.erb
<h1>Google#distance</h1>
<%= form_tag(google_distance_path, method: :get) do %>
	
	<label>Origin:</label><br>
	<%=text_field_tag :origin, params[:origin] %><br>

	<label>Destination:</label><br>
	<%=text_field_tag :destination, params[:destination] %><br>

	<%=submit_tag "submit"%>

<%end%>
<%if !@result.nil?%>
	<h3>Distance is <%= @result["rows"][0]["elements"][0]["distance"]["text"]%></h3>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkingApi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/weather/search.html.erb
<h2>Enter City Name</h2>

<%= form_tag(weather_search_path, method: :get) do %>
	<label>City:</label><br>
	<%= text_field_tag :name%><br>

	<%=submit_tag "search"%>

<%end%>
<% if !@result.nil?%>
	<h3>The temperature in <%= params[:name]%> is <%= @result["main"]["temp"]%></h3>
	<%end%>